name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Wisz dokładnie: DESTROY"
        required: true
        default: "NO"
        type: string

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.8.5"
  AWS_REGION: "eu-central-1"
  TF_WORKING_DIR: "."

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest

    if: github.event.inputs.confirm == 'DESTROY'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::041285314315:role/TerraformCICD
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform plan -destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -destroy -out=tfplan-destroy

      - name: Terraform destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve
